### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by what4893** [Jaspersoft/jrs-rest-php-client#15]
Retrieving the InputControls for a report that doesn't have any results in this error since Jasper doesn't return a valid JSON response (No input controls values found for the report /TestReport), and the code assumes it will.

**Comment by grantbacon** [comment]
Hi, @what4893. This issue has been addressed in a recent commit, 37c25d5c511b922 and 3096d0bb5b926363c
